課題ファイル提出
yuukitsujimura/LinuxCommandPractice pull request #1
Opened 2024-06-12 10:30 UTC by yuukitsujimura

# カリキュラム名
Linuxコマンド
# やったこと/レビュー観点
Linuxコースに取り組みました

2024-06-12 10:38 UTC, cin-sakino requested changes
いくつかコメントさせていただきましたのでご確認お願いいたします！

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +cd LinuxCommandPractice
移動するコマンドのみになってしまっているので、ディレクトリを追加するコマンドも追加しましょう！

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +/Users/tsujimurayuuki/geekationWorkspace/geekation_orientation
ディレクトリのパスを記載するのではなく、**パスを表示するコマンド**を記載してください。

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +mkdir practice_dir_2
これだと直下にディレクトリを作成してしまいます。
`practice_dir_1`の配下にディレクトリを作るようなコマンドにしましょう！

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +mkdir ./ practice_dir_1 practice_dir_2
ディレクトリを作成するコマンドになってしまっています

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +cd ../..
おそらく現在は`LinuxCommandPractice`にいる想定なので、この指定の仕方だと親の方に行ってしまうと思います

2024-06-12 10:38 UTC, cin-sakino commented on answer.sh
> +../..
ファイルを移動させるコマンドを書いてください

2024-06-16 08:36 UTC, yuukitsujimura commented
ご確認お願い致します。

2024-06-17 01:14 UTC, cin-sakino commented
何も変更が適応されていないようです。

2024-06-19 06:00 UTC, yuukitsujimura commented
ご確認をお願い致します。

2024-06-19 08:11 UTC, cin-sakino commented
正常に成功していれば以下のようのこのPR画面に表示されるはずです。
もう一度ターミナルの結果を確認してみましょう！
![Uploading スクリーンショット 2024-06-19 17.10.59.png…]()

2024-06-19 22:52 UTC, yuukitsujimura commented
ありがとうございます。
ご確認お願い致します。

2024-06-20 02:35 UTC, cin-sakino commented
[ここの指摘](https://github.com/yuukitsujimura/LinuxCommandPractice/pull/1/files#r1636222879)がまだ修正されていないようです。

このように指摘に対してスタンプを使って修正漏れがないようにしましょう！
<img width="884" alt="スクリーンショット 2024-06-20 11 35 29" src="https://github.com/yuukitsujimura/LinuxCommandPractice/assets/126738783/84cc22e0-3c05-4e63-9b41-b7b8dc204b68">

2024-06-20 22:32 UTC, yuukitsujimura commented
6/21（金）
おはようございます。
何度も申し訳ありません。
ご確認お願い致します。

2024-06-23 22:57 UTC, merged

2024-06-23 22:58 UTC, yuukitsujimura commented
6/24
おはようございます。
今週も宜しくお願い致します。
ご確認お願い致します。