様々なLinux Command 修正①
yuukitsujimura/LinuxCommandPractice pull request #5
Opened 2024-07-03 08:18 UTC by yuukitsujimura

修正しました。
ご確認お願い致します。

2024-07-03 08:37 UTC, cin-sakino requested changes
修正お願いいたします！

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +mkdir path LinuxCommandPractice
`LinuxCommandPractice`に移動するコマンドが抜けています。

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +touch ./practice_dir_2 practice_dir_1
`mkdir`へのパラメータの渡し方が間違っています。
`touch`を使ったファイル作成はこの問題では不要です。

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +mkdir ./ practice_dir_1 practice_dir_2
ディレクトリを作成するのではなく、ディレクトリの中身を確認することを指示されています。

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +touch ./LinuxCommandPractice practice_file1.txt practice_file2.txt
この指定方法はあっていますか？

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +cd ../../..
practice_dir_2は子ディレクトリだと思うので`..`はおかしいと思います。

2024-07-03 08:37 UTC, cin-sakino commented on answer.sh
> +cd ../..
自分自身が移動するのではなくファイルを移動させるよう指示されています。

2024-07-07 01:54 UTC, yuukitsujimura reviewed
ご確認お願い致します。

2024-07-08 04:41 UTC, yuukitsujimura commented
失礼しました。
ご確認をお願い致します。

2024-07-19 10:18 UTC, uchiyama4929 requested changes

2024-07-19 10:18 UTC, uchiyama4929 commented on answer.sh
> +mv LinuxCommandPractice
mvコマンドはファイルの場所を別のディレクトリに移動させたりするコマンドになります。
こちらでは
フォルダを作成するコマンド
ターミナルの表示階層を移動するコマンド
の順に実行するように書いてください。

2024-07-19 10:18 UTC, uchiyama4929 commented on answer.sh
> +touch ./practice_dir_2/practice_file1.txt/practice_file2.txt
`touch ./practice_dir_2/practice_file1.txt/practice_file2.txt`

```/```で区切るのはディレクトリになりますのでこれではエラーになってしまいます。

またpractice_dir2も直下のディレクトリではないので1から順番に指定するようにしてください。

2024-07-19 10:18 UTC, uchiyama4929 commented on answer.sh
> +cd ./
このコマンドだと移動せずに終わってしまうので修正してください。

ずっとLinuxCommandPractice階層で操作をしていたかと思いますので作成した2つ下の階層まで一気に移動するコマンドを記載してください。

2024-07-19 10:18 UTC, uchiyama4929 commented on answer.sh
> +practice_file1.txtadd commit push ../..
先ほどもありましたがファイルやフォルダを移動させる場合は```mv```コマンドになります。

2024-07-19 10:18 UTC, uchiyama4929 commented on answer.sh
> +rm -r ../../practice_file2.txt
削除する対象はカレントディレクトリ(現在いる場所)のファイルです。

practice_file2.txtは一つ前にcpコマンドでコピーしていて2つの箇所に存在しているので削除対象に注意してください。

2024-07-23 07:18 UTC, yuukitsujimura commented
届いてますでしょうか？

2024-07-23 07:23 UTC, yuukitsujimura commented on answer.sh
> +mv LinuxCommandPractice
end

2024-07-23 08:17 UTC, merged